return {
  -- http://www1.folha.uol.com.br/poder/2016/05/1774182-juca-nao-falou-sobre-economia-ao-citar-sangria-ouca.shtml
  {'Sérgio Machado', "Acontece o seguinte, objetivamente falando, com o negócio que o Supremo fez [autorizou prisões logo após decisão de segunda instância], vai todo mundo delatar."},
  {'Romero Jucá', "Exatamente, e vai sobrar muito. O Marcelo, e a Odebrecht, vão fazer."},
  {'Machado', "Odebrecht vai fazer."},
  {'Jucá', "Seletiva, mas vai fazer."},
  {'Machado', "A Camargo vai fazer ou não. Eu estou muito preocupado porque eu acho que... O Janot está a fim de pegar vocês. E acha que eu sou o caminho."},
  {'Jucá', "[inaudível]"},
  {'Machado', "Hum?"},
  {'Jucá', "Mas como é que está sua situação?"},
  {'Machado', "Minha situação não tem nada, não pegou nada, mas ele quer jogar tudo pro Moro. Como não tem nada e como eu estou desligado..."},
  {'Jucá', "É, não tem conexão né..."},
  {'Machado', "Não tem conexão, aí joga pro Moro. Aí fodeu. Aí fodeu para todo mundo. Como montar uma estrutura para evitar que eu &quot;desça&quot;? Se eu descer..."},
  {'Jucá', "O que que você acha? Como é que voc..."},
  {'Machado', "Eu queria discutir com vocês. Eu cheguei a essa conclusão essa semana. Ele acha que eu sou o caixa de vocês, o Janot. Janot não vale &quot;cibazol&quot; [algo sem valor]. Quem esperar que ele vai ser amigo, não vai... [...] E ele está visando o Renan e vocês. E acha que eu sou o canal. Não encontrou nada, não tem nada."},
  {'Jucá', "Nem vai encontrar, né, Sérgio."},
  {'Machado', "Não encontrou nada, não tem nada, mas acha... O que é que faz? Como tem aquela delação do Paulo Roberto dos 500 mil e tem a delação do Ricardo, que é uma coisa solta, ele quer pegar essas duas coisas. 'Não tem nada contra os senadores, joga ele para baixo' [Curitiba]. Tem que encontrar uma maneira..."},
  {'Jucá', "Você tem que ver com seu advogado como é que a gente pode ajudar. [...] Tem que ser política, advogado não encontra [inaudível]. Se é político, como é a política? Tem que resolver essa porra... Tem que mudar o governo pra poder estancar essa sangria."},
  {'Machado', "Tem que ser uma coisa política e rápida. Eu acho que ele está querendo... o PMDB. Prende, e bota lá embaixo. Imaginou?"},
  {'Jucá', "Você conversou com o Renan?"},
  {'Machado', "Não, quis primeiro conversar contigo porque tu é o mais sensato de todos."},
  {'Jucá', "Eu acho que a gente precisa articular uma ação política."},
  {'Machado', "..quis conversar primeiro contigo, que tenho maior intimidade. Depois eu quero conversar com Sarney e o Renan, com vocês três. [...] Eu estou convencido, com essa sinalização que conseguiu do Eduardo [incompreensível]. Desvincula do Renan."},
  {'Jucá', "Mas esse negócio do Eduardo está atacando [incompreensível]."},
  {'Machado', "Mas ele [Janot] está querendo pegar vocês, tenho certeza absoluta."},
  {'Jucá', "Não tem duas dúvidas."},
  {'Machado', "Não, tenho certeza absoluta. E ele não vale um 'cibazol'. É um cara raivoso, rancoroso e etc. Então como é que ele age? Como não encontrou nada nem vai encontrar. [inaudível]"},
  {'Jucá', "O Moro virou uma 'Torre de Londres'."},
  {'Machado', "Torre de Londres."},
  {'Jucá', "Mandava o coitado pra lá para o cara confessar."},
  {'Machado', "Pro cara confessar. Então a gente tem que agir como [incompreensível] e pensar numa fórmula para encontrar uma solução para isso."},
  {'Jucá', "Converse com ele [Renan], converse com o Sarney, ouça eles, e vamos sentar pra gente..."},
  {'Machado', "Isso, Romero, o que eu acho primeiro: que é bom pra gente.<br>"},
  {'Jucá', "Eu acho que você deveria procurar o Sarney, devia procurar o Renan,e a gente voltar a conversar depois. [incompreensível] 'como é que é'."},
  {'Machado', "É porque... Se descer, Romero, não dá."},
  {'Jucá', "Não é um desastre porque não tem nada a ver. Mas é um desgaste, porque você, pô, vai ficar exposto de uma forma sem necessidade. [...]"},
  {'Machado', "O Marcelo, o dono do Brasil, está preso há um ano. Sacanagem com Marcelo, rapaz, nunca vi coisa igual. Sacanagem com aquele André Esteves, nunca vi coisa igual."},
  {'Jucá', "Rapaz... [concordando]"},
  {'Machado', "Outra coisa. A frouxidão de vocês em prender o Delcídio foi um negócio inacreditável. [O Senado concordou com prisão decretada pelo STF]"},
  {'Jucá', "Sim, pô, não adianta soltar o Delcidio, aí o PT dá uma nota, tira o cara, diz que o cara é culpado, como é que você segura uma porra dentro do plenário?"},
  {'Machado', "Mas o cara não foi preso em flagrante, tem que respeitar a lei. Respeito à lei, a lei diz clara..."},
  {'Jucá', "Pô, pois então. Ali não teve jeito não. A hora que o PT veio, entendeu, puxou o tapete dele, o Rui, a imprensa toda, os caras não seguraram, não."},
  {'Machado', "Eu sei disso, foi uma cagada."},
  {'Jucá', "Foi uma cagada geral."},
  {'Machado', "Foi uma cagada geral. Foi uma cagada o Supremo fazer o que fez com o negócio de prender em segunda instância, isso é absurdo total que não que não dá interpretar, e ninguém fez nada. Ninguém fez ADIN, ninguém se questionou. Isso aí é para precipitar as delações. Romero, esquentou as delações, não escapa pedra..."},
  {'Jucá', "[incompreensível] no Brasil."},
  {'Machado', "Não escapa pedra sobre pedra.<br>"},
  {'Machado', "Eu estou com todos os certificados do TCU, agora me deram, não devo nada, zero. E isso adianta alguma coisa? Então estou preocupado."},
  {'Jucá', "Não, tem que cuidar mesmo."},
  {'Machado', "Eu estou preocupado porque estou vendo que esse negócio da filha do Eduardo, da mulher, foi uma advertência para mim. E das histórias que estou sabendo, o interesse é pegar vocês. Nós. E o Renan, sobretudo."},
  {'Jucá', "Não, o alvo na fila é o Renan. Depois do Eduardo Cunha... É o Eduardo Cunha, a Dilma, e depois é o Renan."},
  {'Machado', "E ele [Janot] não tem nada. Se ele tivesse alguma coisa, ele ia me manter aqui em cima, para poder me forçar aqui em cima, porque ele não vai dar esse troféu pro Moro. Como ele não tem nada, ele quer ver se o Moro arranca..."},
  {'Jucá', "..para subir de novo."},
  {'Machado', "..para poder subir de novo. É esse o esquema. Agora, como fazer? Porque arranjar uma imunidade não tem como, não tem como. A gente tem que ter a saída porque é um perigo. E essa porra... A solução institucional demora ainda algum tempo, não acha?"},
  {'Jucá', "Tem que demorar três ou quatro meses no máximo. O país não aguenta mais do que isso, não."},
  {'Machado', "Rapaz, a solução mais fácil era botar o Michel."},
}
